apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-token-service
  namespace: caritas
  labels:
    app: livekit-token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit-token-service
  template:
    metadata:
      labels:
        app: livekit-token-service
    spec:
      containers:
      - name: token-service
        image: livekit-token-service:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3010
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3010
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: livekit-token-service
  namespace: caritas
  labels:
    app: livekit-token-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3010
    targetPort: 3010
    nodePort: 30101
    protocol: TCP
  selector:
    app: livekit-token-service


