apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: caritas
data:
  livekit.yaml: |
    port: 7880
    bind_addresses:
      - "0.0.0.0"

    rtc:
      port_range_start: 50000
      port_range_end: 50100
      use_external_ip: true
      tcp_port: 7881
      enable_tcp_candidates: true
      force_tcp: true
      
    room:
      auto_create: true
      empty_timeout: 300
      max_participants: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: caritas
  labels:
    app: livekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit
  template:
    metadata:
      labels:
        app: livekit
    spec:
      hostNetwork: true  # CRITICAL: Use host network for WebRTC UDP ports
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: livekit
        image: livekit/livekit-server:latest
        imagePullPolicy: Always
        env:
        - name: LIVEKIT_KEYS
          value: "APIm7qGJ8kR3fN2pL5tX: secretW9vY4bH6nK8mP2qR7sT3xZ5A1B2C3D4E5F6G7H8"
        - name: LIVEKIT_PORT
          value: "7880"
        - name: LIVEKIT_RTC_PORT_RANGE_START
          value: "50000"
        - name: LIVEKIT_RTC_PORT_RANGE_END
          value: "50100"
        - name: LIVEKIT_NODE_IP
          value: "91.99.219.182"  # External IP for WebRTC
        ports:
        - name: http
          containerPort: 7880
          protocol: TCP
        - name: rtc-start
          containerPort: 50000
          protocol: UDP
        - name: rtc-end
          containerPort: 50100
          protocol: UDP
        resources:
          requests:
            memory: "2Gi"      # Increased for 6+ users
            cpu: "2000m"       # 2 CPU cores minimum
          limits:
            memory: "8Gi"      # Allow bursts for heavy usage
            cpu: "6000m"       # 6 CPU cores for 6+ users
        livenessProbe:
          httpGet:
            path: /
            port: 7880
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7880
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: caritas
  labels:
    app: livekit
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7880
    targetPort: 7880
    protocol: TCP
  selector:
    app: livekit
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livekit-ingress
  namespace: caritas
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - livekit.oriso.site
    secretName: livekit-tls
  rules:
  - host: livekit.oriso.site
    http:
      paths:
      # MatrixRTC Authorization Service (LiveKit JWT)
      - path: /livekit/jwt
        pathType: Prefix
        backend:
          service:
            name: livekit-token-service
            port:
              number: 3010
      # LiveKit SFU websocket
      - path: /
        pathType: Prefix
        backend:
          service:
            name: livekit
            port:
              number: 7880

