name: CI - Main

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  ORG: openresilienceinitiative

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Validate token service
      uses: ./.github/actions/node-validate
      with:
        node_version: '20'

    - name: Create and Publish Docker image
      uses: ./.github/actions/docker-build-push
      with:
        push_to_ghcr: true
        image_name: livekit-token-service
        github_token: ${{ secrets.GITHUB_TOKEN }}
        context_dir: token-service
